default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: pipeline_ci_cd_development

test:
  <<: *default
  database: pipeline_ci_cd_test

production:
  <<: *default
  database: pipeline_ci_cd_production
  username: pipeline_ci_cd
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
