name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: pipeline_ci_cd_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with: POSTGRES_DB
        node-version: 12.22.9

    - name: Install dependencies
      run: |
        gem install bundler
        bundler install
        yarn install --ignore-dependencies

    - name: Set up database
      env:
        RAILS_ENV: development
        DATABASE_URL: postgres://postgres:password@postgres:5432/pipeline_ci_cd_development
      run:
        bin/rails db:create db:schema:load

    - name: Run tests
      env:
        RAILS_ENV: development
      run:
        bin/rails test